/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddCaption: typeof import('./src/components/addCaption/index.vue')['default']
    AddPic: typeof import('./src/components/addPic/index.vue')['default']
    AddPicDialog: typeof import('./src/components/addPicDialog/index.vue')['default']
    AddTxtDialog: typeof import('./src/components/addTxtDialog/index.vue')['default']
    DContextmenu: typeof import('./src/components/vue3VideoPlay/components/d-contextmenu.vue')['default']
    DIcon: typeof import('./src/components/vue3VideoPlay/components/d-icon.vue')['default']
    DLoading: typeof import('./src/components/vue3VideoPlay/components/d-loading.vue')['default']
    DPlayerTop: typeof import('./src/components/vue3VideoPlay/components/d-player-top.vue')['default']
    DSlider: typeof import('./src/components/vue3VideoPlay/components/d-slider.vue')['default']
    DStatus: typeof import('./src/components/vue3VideoPlay/components/d-status.vue')['default']
    DSwitch: typeof import('./src/components/vue3VideoPlay/components/d-switch.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElText: typeof import('element-plus/es')['ElText']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    Main: typeof import('./src/components/vue3VideoPlay/video-play/main.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
